name: Tests

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches: [ master ]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.4.0
        with:
          args: --format=txt --diff --dry-run --using-cache=no --verbose .

  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Trim dependency
        run: composer remove --dev friendsofphp/php-cs-fixer

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: ./vendor/bin/pest --ci
