name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.4.0
        with:
          args: --format=txt --diff --dry-run --using-cache=no --verbose .